version: '3.8'

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
    environment:
      - TOKEN=${TOKEN}
      - GUILDS=${GUILDS}
    tty: true
    command: ["python3", "main.py"]
    restart: always